In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [3]:
type(list1)

list

In [4]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
np.arange(100, 0, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [12]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [13]:
arr3.size

10

In [14]:
arr3.dtype

dtype('int32')

In [15]:
arr3.nbytes

40

In [16]:
len(arr3)

10

In [17]:
arr3.ndim

1

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [21]:
a = np.array([10, 20, 30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [22]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [23]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
ar1 = np.arange(0, 22)
ar1[ar1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
np.linspace(10, 20, 4) #eşit aralıklı sayılar oluşturur

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [28]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [29]:
np.random.random(4)

array([0.17994287, 0.02764017, 0.89811116, 0.99095014])

In [30]:
np.random.randint(0, 500, 5)

array([177, 254, 427, 269,  85])

In [31]:
np.random.randint(0, 500, 10)

array([287, 354,  98, 463, 130, 266, 128, 420, 304, 227])

In [32]:
#seed

In [33]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [35]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [36]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [37]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [38]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [39]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [41]:
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [42]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [43]:
#Normal Dağılım (mean = 0, variance = 1)
b2 = np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [44]:
arr1

array([10, 20, 30, 40, 50, 60])

In [45]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [46]:
arr2 = np.arange(0, 20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
arr2.sum()

190

In [48]:
np.cumsum(arr2)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)

In [49]:
#min(), max(), argmin(), argmax(), mean(), median(), var()

In [50]:
np.std(arr2)

5.766281297335398

In [51]:
A = np.array([[1,2,3,0], [5,6,7,22], [10, 11, 1, 13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [52]:
A.sum()

129

In [53]:
A.max()

22

In [54]:
A.min()

0

In [55]:
np.amin(A, axis = 0) #sütun bazlı minimum değer

array([1, 2, 1, 0])

In [56]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [57]:
A.mean()

8.0625

In [58]:
np.mean(A)

8.0625

In [59]:
np.median(A)

6.5

In [60]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [61]:
#Bir dizinin elemanlarını okuma

In [62]:
a = np.array([7, 5, 3, 9, 0, 2])
a

array([7, 5, 3, 9, 0, 2])

In [63]:
a[0]

7

In [64]:
a[1:4]

array([5, 3, 9])

In [65]:
a[-1]

2

In [66]:
a[-3:-1]

array([9, 0])

In [67]:
#Dizi içerisindeki elemanları değiştirme

In [68]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [69]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [70]:
ar2 = np.array([10,20,30,10,10,20,20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [71]:
rep2 = np.where(ar2 == 10, 99 ,ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [72]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [73]:
np.put(p2, [0,3,5], [33,55,99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [74]:
#Eksik değerler ile ilgilenme

In [75]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [76]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [77]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [78]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [79]:
np.isnan(a).any()

False

In [80]:
A = np.array([[1,2,np.nan,4], [np.nan,6,7,8], [10, np.nan, 12, 13], [14, 15, 16, 17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [81]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [82]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [83]:
#Dizileri Birleştirme

In [84]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1, 20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [85]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [86]:
np.vstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [87]:
np.hstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [88]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [89]:
np.intersect1d(c1, c2)

array([20, 40, 60])

In [90]:
np.setdiff1d(c1, c2)

array([10, 30, 50])

In [91]:
#Farklı durumlara göre eleman işleme

In [92]:
a = np.array([1, 2, 3, 6, 8])
b = np.array([10, 2, 30, 60, 8])

np.where(a == b)

(array([1, 4], dtype=int64),)

In [93]:
a[np.where(a == b)]

array([2, 8])

In [94]:
a1 = np.arange(0, 60)
a1[np.where((a1 > 20) & (a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [95]:
a1 = np.arange(0, 60)
a1[np.where(((a1 > 20) & (a1 < 35)) | (a1 % 10 == 0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [96]:
a1[np.where(np.logical_and(a1 > 20, a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [97]:
#isin() fonksiyonu

In [98]:
a = np.array([10,20,30,40,50,60,70])
a

array([10, 20, 30, 40, 50, 60, 70])

In [99]:
np.isin(a, [11,20])

array([False,  True, False, False, False, False, False])

In [100]:
a[np.isin(a, 20)]

array([20])

In [101]:
np.isin(a, 33)

array([False, False, False, False, False, False, False])

In [102]:
a[np.isin(a, 33)]

array([], dtype=int32)

In [103]:
#Dizileri Ters Çevirme

In [104]:
a4 = np.arange(10, 30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [105]:
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [106]:
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [107]:
a3 = np.array([[3,2,8,1], [70, 50, 10, 67], [45, 25, 75, 15], [12, 9, 77 ,4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [108]:
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [109]:
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [110]:
a3[::-1, ::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [111]:
#Dizileri Sıralama

In [112]:
a = np.array([10, 5, 2, 22, 12, 92, 17, 33])
a

array([10,  5,  2, 22, 12, 92, 17, 33])

In [113]:
np.sort(a) #artan sıralama, ascending

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [114]:
b = np.sort(a)
b = b[::-1]
b

array([92, 33, 22, 17, 12, 10,  5,  2])

In [116]:
c = np.sort(a)
np.flip(c)

array([92, 33, 22, 17, 12, 10,  5,  2])

In [117]:
a[::-1].sort()
a

array([92, 33, 22, 17, 12, 10,  5,  2])

In [118]:
a3 = np.array([[3,2,8,1], [70,50,10,67], [45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [119]:
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [120]:
np.sort(a3, axis = 1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [121]:
np.sort(a3, axis = 0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [122]:
#Bir dizi içerisindeki tekrar eden elemanları bulmak

In [123]:
b = np.array([10,10,10,20,30,20,30,30,20,10,10,30,10])
np.unique(b)

array([10, 20, 30])

In [125]:
val, count = np.unique(b, return_counts = True)
val , count

(array([10, 20, 30]), array([6, 3, 4], dtype=int64))

In [126]:
np.bincount(b).argmax()

10